//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MaCTHD { get; set; }
        public string SoHD { get; set; }
        public string MaHH { get; set; }
        public int SoLuong { get; set; }
        public double KG { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual HoaDonVanChuyen HoaDonVanChuyen { get; set; }
    }
}
