//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTVanChuyen
    {
        public string MaCTVC { get; set; }
        public string SoHD { get; set; }
        public string MaNK { get; set; }
        public Nullable<System.DateTime> NgayNhapKho { get; set; }
        public Nullable<System.DateTime> NgayXuatKho { get; set; }
    
        public virtual NhaKho NhaKho { get; set; }
        public virtual HoaDonVanChuyen HoaDonVanChuyen { get; set; }
    }
}
