//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyGiaoHangEntities : DbContext
    {
        public QuanLyGiaoHangEntities()
            : base("name=QuanLyGiaoHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_Role> CT_Role { get; set; }
        public virtual DbSet<CT_TuyenDuong> CT_TuyenDuong { get; set; }
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<CTVanChuyen> CTVanChuyens { get; set; }
        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<HoaDonVanChuyen> HoaDonVanChuyens { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhachNhan> KhachNhans { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<LoaiHH> LoaiHHs { get; set; }
        public virtual DbSet<LoaiVanChuyen> LoaiVanChuyens { get; set; }
        public virtual DbSet<NhaKho> NhaKhoes { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuGuiHang> PhieuGuiHangs { get; set; }
        public virtual DbSet<PhieuYeuCau> PhieuYeuCaus { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TuyenDuong> TuyenDuongs { get; set; }
        public virtual DbSet<UserKH> UserKHs { get; set; }
    
        public virtual ObjectResult<Check_SDTKH_Result> Check_SDTKH(string sDT)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_SDTKH_Result>("Check_SDTKH", sDTParameter);
        }
    
        public virtual ObjectResult<Show_LoaiVC_Result> Show_LoaiVC(string maLVC)
        {
            var maLVCParameter = maLVC != null ?
                new ObjectParameter("MaLVC", maLVC) :
                new ObjectParameter("MaLVC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Show_LoaiVC_Result>("Show_LoaiVC", maLVCParameter);
        }
    
        public virtual ObjectResult<Show_Phongban_Result> Show_Phongban(string mapb)
        {
            var mapbParameter = mapb != null ?
                new ObjectParameter("Mapb", mapb) :
                new ObjectParameter("Mapb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Show_Phongban_Result>("Show_Phongban", mapbParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int USP_AddCT_HD(string soHD, string maHH, Nullable<int> sL, Nullable<int> kG)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            var maHHParameter = maHH != null ?
                new ObjectParameter("MaHH", maHH) :
                new ObjectParameter("MaHH", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            var kGParameter = kG.HasValue ?
                new ObjectParameter("KG", kG) :
                new ObjectParameter("KG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_AddCT_HD", soHDParameter, maHHParameter, sLParameter, kGParameter);
        }
    
        public virtual int USP_AddCTVC(string soHd, string maNK)
        {
            var soHdParameter = soHd != null ?
                new ObjectParameter("SoHd", soHd) :
                new ObjectParameter("SoHd", typeof(string));
    
            var maNKParameter = maNK != null ?
                new ObjectParameter("MaNK", maNK) :
                new ObjectParameter("MaNK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_AddCTVC", soHdParameter, maNKParameter);
        }
    
        public virtual int USP_AddHangHoa(string tenHH, string donVT, string maLHH, Nullable<int> giaTien)
        {
            var tenHHParameter = tenHH != null ?
                new ObjectParameter("TenHH", tenHH) :
                new ObjectParameter("TenHH", typeof(string));
    
            var donVTParameter = donVT != null ?
                new ObjectParameter("DonVT", donVT) :
                new ObjectParameter("DonVT", typeof(string));
    
            var maLHHParameter = maLHH != null ?
                new ObjectParameter("MaLHH", maLHH) :
                new ObjectParameter("MaLHH", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_AddHangHoa", tenHHParameter, donVTParameter, maLHHParameter, giaTienParameter);
        }
    
        public virtual ObjectResult<USP_CheckDon_Result> USP_CheckDon(string soHD)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CheckDon_Result>("USP_CheckDon", soHDParameter);
        }
    
        public virtual int USP_CreatePhieuGui(string tenKH, string sDTKH, string diaChiKH, Nullable<bool> gioiTinhKH, string tenKN, string sDTKN, string diaChiKN, Nullable<bool> gioiTinhKN, string maLVC, string maNK, Nullable<bool> cOD, string maNV)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var sDTKHParameter = sDTKH != null ?
                new ObjectParameter("SDTKH", sDTKH) :
                new ObjectParameter("SDTKH", typeof(string));
    
            var diaChiKHParameter = diaChiKH != null ?
                new ObjectParameter("DiaChiKH", diaChiKH) :
                new ObjectParameter("DiaChiKH", typeof(string));
    
            var gioiTinhKHParameter = gioiTinhKH.HasValue ?
                new ObjectParameter("GioiTinhKH", gioiTinhKH) :
                new ObjectParameter("GioiTinhKH", typeof(bool));
    
            var tenKNParameter = tenKN != null ?
                new ObjectParameter("TenKN", tenKN) :
                new ObjectParameter("TenKN", typeof(string));
    
            var sDTKNParameter = sDTKN != null ?
                new ObjectParameter("SDTKN", sDTKN) :
                new ObjectParameter("SDTKN", typeof(string));
    
            var diaChiKNParameter = diaChiKN != null ?
                new ObjectParameter("DiaChiKN", diaChiKN) :
                new ObjectParameter("DiaChiKN", typeof(string));
    
            var gioiTinhKNParameter = gioiTinhKN.HasValue ?
                new ObjectParameter("GioiTinhKN", gioiTinhKN) :
                new ObjectParameter("GioiTinhKN", typeof(bool));
    
            var maLVCParameter = maLVC != null ?
                new ObjectParameter("MaLVC", maLVC) :
                new ObjectParameter("MaLVC", typeof(string));
    
            var maNKParameter = maNK != null ?
                new ObjectParameter("MaNK", maNK) :
                new ObjectParameter("MaNK", typeof(string));
    
            var cODParameter = cOD.HasValue ?
                new ObjectParameter("COD", cOD) :
                new ObjectParameter("COD", typeof(bool));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CreatePhieuGui", tenKHParameter, sDTKHParameter, diaChiKHParameter, gioiTinhKHParameter, tenKNParameter, sDTKNParameter, diaChiKNParameter, gioiTinhKNParameter, maLVCParameter, maNKParameter, cODParameter, maNVParameter);
        }
    
        public virtual int USP_DeleteHD_SoHD(string soHD)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_DeleteHD_SoHD", soHDParameter);
        }
    
        public virtual ObjectResult<string> USP_MaNV(string tenTK)
        {
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_MaNV", tenTKParameter);
        }
    
        public virtual ObjectResult<USP_ShowCT_HD_Result> USP_ShowCT_HD(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowCT_HD_Result>("USP_ShowCT_HD", maHDParameter);
        }
    
        public virtual ObjectResult<USP_ShowCTVC_MaNK_Result> USP_ShowCTVC_MaNK(string maNK)
        {
            var maNKParameter = maNK != null ?
                new ObjectParameter("MaNK", maNK) :
                new ObjectParameter("MaNK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowCTVC_MaNK_Result>("USP_ShowCTVC_MaNK", maNKParameter);
        }
    
        public virtual ObjectResult<USP_ShowDonHang_Result> USP_ShowDonHang(string soHD, string maNK)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            var maNKParameter = maNK != null ?
                new ObjectParameter("MaNK", maNK) :
                new ObjectParameter("MaNK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowDonHang_Result>("USP_ShowDonHang", soHDParameter, maNKParameter);
        }
    
        public virtual ObjectResult<USP_ShowHH_TenHH_Result> USP_ShowHH_TenHH(string tenHH)
        {
            var tenHHParameter = tenHH != null ?
                new ObjectParameter("TenHH", tenHH) :
                new ObjectParameter("TenHH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowHH_TenHH_Result>("USP_ShowHH_TenHH", tenHHParameter);
        }
    
        public virtual ObjectResult<USP_ShowItemQL_Result> USP_ShowItemQL(string maNK)
        {
            var maNKParameter = maNK != null ?
                new ObjectParameter("MaNK", maNK) :
                new ObjectParameter("MaNK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowItemQL_Result>("USP_ShowItemQL", maNKParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> USP_ShowKG(string soHD)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("USP_ShowKG", soHDParameter);
        }
    
        public virtual ObjectResult<USP_ShowLoaiHH_MaLHH_Result> USP_ShowLoaiHH_MaLHH(string maLHH)
        {
            var maLHHParameter = maLHH != null ?
                new ObjectParameter("MaLHH", maLHH) :
                new ObjectParameter("MaLHH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowLoaiHH_MaLHH_Result>("USP_ShowLoaiHH_MaLHH", maLHHParameter);
        }
    
        public virtual ObjectResult<USP_ShowNhaKho_Result> USP_ShowNhaKho(string maKv)
        {
            var maKvParameter = maKv != null ?
                new ObjectParameter("MaKv", maKv) :
                new ObjectParameter("MaKv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowNhaKho_Result>("USP_ShowNhaKho", maKvParameter);
        }
    
        public virtual ObjectResult<USP_ShowPhieuGui_SoPGH_Result> USP_ShowPhieuGui_SoPGH(string soPGH)
        {
            var soPGHParameter = soPGH != null ?
                new ObjectParameter("SoPGH", soPGH) :
                new ObjectParameter("SoPGH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowPhieuGui_SoPGH_Result>("USP_ShowPhieuGui_SoPGH", soPGHParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> USP_ShowTongTien_SoHD(string soHD)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("USP_ShowTongTien_SoHD", soHDParameter);
        }
    
        public virtual ObjectResult<USP_TimHD_Result> USP_TimHD(string soHD)
        {
            var soHDParameter = soHD != null ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_TimHD_Result>("USP_TimHD", soHDParameter);
        }
    }
}
