//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonVanChuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonVanChuyen()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.CTVanChuyens = new HashSet<CTVanChuyen>();
        }
    
        public string SoHD { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<long> TongTien { get; set; }
        public string SoPGH { get; set; }
        public string MaNV { get; set; }
        public bool TrangThai { get; set; }
        public string MaTD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTVanChuyen> CTVanChuyens { get; set; }
        public virtual PhieuGuiHang PhieuGuiHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TuyenDuong TuyenDuong { get; set; }
    }
}
