//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NhaKho
    {
        QuanLyGiaoHangEntities data = new QuanLyGiaoHangEntities();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaKho()
        {
            this.CT_TuyenDuong = new HashSet<CT_TuyenDuong>();
            this.CTVanChuyens = new HashSet<CTVanChuyen>();
            this.NhanViens = new HashSet<NhanVien>();
        }
        public NhaKho(string MaNK)
        {
            NhaKho nk = data.NhaKhoes.FirstOrDefault(n => n.MaNK.Equals(MaNK));
            MaNK = nk.MaNK;
            TenNK = nk.TenNK;
            DienTich = nk.DienTich;
            SucChua = nk.SucChua;
            MaKV = nk.MaKV;
            DiaChi = nk.DiaChi;
        }
        public string MaNK { get; set; }
        public string TenNK { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<int> SucChua { get; set; }
        public string DiaChi { get; set; }
        public string MaKV { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TuyenDuong> CT_TuyenDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTVanChuyen> CTVanChuyens { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
