//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuYeuCau
    {
        public string SoPYC { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaKH { get; set; }
        public Nullable<decimal> KhoiLuong { get; set; }
        public string MaKN { get; set; }
        public string MaLVC { get; set; }
        public Nullable<long> ThanhToan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhachNhan KhachNhan { get; set; }
        public virtual LoaiVanChuyen LoaiVanChuyen { get; set; }
    }
}
