//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGuiHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuGuiHang()
        {
            this.HoaDonVanChuyens = new HashSet<HoaDonVanChuyen>();
        }
    
        public string SoPGH { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<bool> COD { get; set; }
        public string MaKH { get; set; }
        public string MaLVC { get; set; }
        public string MaNV { get; set; }
        public string MaKN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonVanChuyen> HoaDonVanChuyens { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhachNhan KhachNhan { get; set; }
        public virtual LoaiVanChuyen LoaiVanChuyen { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
