//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuyenDuong()
        {
            this.CT_TuyenDuong = new HashSet<CT_TuyenDuong>();
            this.HoaDonVanChuyens = new HashSet<HoaDonVanChuyen>();
        }
    
        public string MaTD { get; set; }
        public string TenTD { get; set; }
        public int ThoiGian { get; set; }
        public string MaKhoBD { get; set; }
        public string MaKhoKT { get; set; }
        public string MaLVC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TuyenDuong> CT_TuyenDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonVanChuyen> HoaDonVanChuyens { get; set; }
        public virtual LoaiVanChuyen LoaiVanChuyen { get; set; }
    }
}
