//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangTietKiem.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UserKH
    {
        public UserKH() { }
        public string SDT { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string MaKH { get; set; }
        public string UserName { get; set; }
        public UserKH(string sDT, string matKhau, string email, string maKH, string userName)
        {
            SDT = sDT;
            MatKhau = matKhau;
            Email = email;
            MaKH = maKH;
            UserName = userName;
        }
        public virtual KhachHang KhachHang { get; set; }
    }
}
